sudo: false

language: go

go:
  - 1.12.x
  - 1.13.x
  - master

env:
  - GO111MODULE=on,KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=600s

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - go get -v go.etcd.io/etcd

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - make ci-check

after_success:
  - bash <(curl -s https://codecov.io/bash)