sudo: true

language: go

go:
  - 1.12.x
  - master

env:
  - GO111MODULE=on KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=120s

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - |
    os=$(go env GOOS)
    arch=$(go env GOARCH)
    version=3.1.0

    curl -O -L https://github.com/kubernetes-sigs/kustomize/releases/download/v${version}/kustomize_${version}_${os}_${arch}

    mv kustomize_*_${os}_${arch} kustomize
    chmod u+x kustomize

    sudo mv kustomize /usr/local/bin
    export PATH=$PATH:/usr/local/bin
  - |
    os=$(go env GOOS)
    arch=$(go env GOARCH)

    curl -sL https://go.kubebuilder.io/dl/2.0.0/${os}/${arch} | tar -xz -C /tmp/

    sudo mv /tmp/kubebuilder_2.0.0_${os}_${arch} /usr/local/kubebuilder
    export PATH=$PATH:/usr/local/kubebuilder/bin

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - make ci-check

after_success:
  - bash <(curl -s https://codecov.io/bash)