sudo: false

language: go

go:
  - 1.11.x
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

script:
  - make ci-check

after_success:
  - bash <(curl -s https://codecov.io/bash)