sudo: false

language: go

go:
  - 1.12.x
  - 1.13.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0

script:
  - make ci-check

after_success:
  - bash <(curl -s https://codecov.io/bash)