sudo: true

language: go

go:
  - 1.12.x
  - master

env:
  - GO111MODULE=on KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=120s

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - |
    opsys=linux  # or darwin, or windows
    curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
      grep browser_download |\
      grep $opsys |\
      cut -d '"' -f 4 |\
      xargs curl -O -L
    mv kustomize_*_${opsys}_amd64 kustomize
    chmod u+x kustomize
    mkdir /usr/local/kustomize/bin
    mv kustomize /usr/local/kustomize/bin
    export PATH=$PATH:/usr/local/kustomize/bin
  - |
    os=$(go env GOOS)
    arch=$(go env GOARCH)

    curl -sL https://go.kubebuilder.io/dl/2.0.0/${os}/${arch} | tar -xz -C /tmp/

    sudo mv /tmp/kubebuilder_2.0.0_${os}_${arch} /usr/local/kubebuilder
    export PATH=$PATH:/usr/local/kubebuilder/bin

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - make ci-check

after_success:
  - bash <(curl -s https://codecov.io/bash)