
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - lbsrcranger.beachape.com
  resources:
  - loadbalancerrangers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lbsrcranger.beachape.com
  resources:
  - loadbalancerrangers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lbsrcranger.beachape.com
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
