
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: lbsrcrangers.lbsrcranger.beachape.com
spec:
  group: lbsrcranger.beachape.com
  names:
    kind: LbSrcRanger
    plural: lbsrcrangers
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LbSrcRanger is the Schema for the lbsrcrangers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LbSrcRangerSpec defines the desired state of LbSrcRanger
          properties:
            src_ip_urls:
              description: SrcIpUrls holds urls that return newline-separated lists
                of IP address (ranges) to use as source ip ranges in the selected
                LoadBalancer serviceds
              items:
                type: string
              type: array
            target_labels:
              additionalProperties:
                type: string
              description: TargetLabels is a selector for finding LoadBalancer Services
                that need tending-to
              type: object
            update_every:
              description: UpdateEvery is the duration to wait between reconciles
              type: string
          required:
          - update_every
          type: object
        status:
          description: LbSrcRangerStatus defines the observed state of LbSrcRanger
          properties:
            last_run_at:
              description: LastRunAt is the time that there was a load balancer run
              format: date-time
              type: string
            last_updated_count:
              description: UpdatedCount is the number of servies last updated
              type: integer
          required:
          - last_run_at
          - last_updated_count
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
